# Generated by Django 4.2.7 on 2023-12-21 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=30)),
                ('telefono', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CantidadSilla', models.PositiveIntegerField(default=0)),
                ('NumeroSala', models.IntegerField(default=0)),
                ('TamanioPantalla', models.CharField(choices=[('50', '50'), ('55', '55'), ('60', '60'), ('65', '65'), ('70', '70'), ('80', '80')], max_length=10)),
                ('InclusividadSala', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=4)),
                ('TipoSala', models.CharField(choices=[('normal', 'Normal'), ('premium', 'Premium'), ('vip', 'Vip')], max_length=10)),
                ('EstadoSala', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado')], max_length=10)),
                ('cine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cine.cine')),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracionFuncion', models.CharField(max_length=20)),
                ('nombreFuncion', models.CharField(max_length=20)),
                ('horarioFuncion', models.CharField(max_length=30)),
                ('tipoFuncion', models.CharField(choices=[('3D', '3D'), ('2D', '2D')], max_length=10)),
                ('generoFuncion', models.CharField(max_length=30)),
                ('restriccionEdad', models.CharField(choices=[('mayor de edad', '+18'), ('TE', 'Todo espectador'), ('mayor de 14', '14')], max_length=30)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cine.sala')),
            ],
        ),
    ]
