# Generated by Django 4.2.7 on 2023-12-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cine',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='sala',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sala',
            name='cine',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sala',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
